name: cd worklow
on: 
  push:
    branches:
     - "main"

jobs:
  cd-workflow:
    name: cd workflow 
    runs-on: ubuntu-latest

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
     
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: mahmoudghanem/java-app:latest
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::123456789100:role/my-github-actions-role
          aws-region: us-east-2    
      - name: depoly to k8s
        run: aws eks update-kubeconfig --region us-east-2 --name eks
        run:  kubectl apply -f ./k8s/deployment.yaml
